In [ ]:
import pandas as pd
import statsmodels.api as sm
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
import numpy as np
import time
from tqdm import tqdm
from lightgbm import LGBMClassifier

### 6개월치 proba 평균

In [ ]:
df_weather=pd.read_csv('기상데이터 0510 index X.csv')
df_weather.head()

,관측일자,temperature,temp_max,temp_min,rainfall,humidity,조사지역,연,월,일
0,1988-01-01,-2.4,-0.8,-4.4,0.5,64.0,서울,1988,1,1
1,1988-01-01,-2.6,0.5,-6.2,1.9,73.0,관악산,1988,1,1
2,1988-01-01,-4.1,-0.7,-8.6,0.0,66.0,춘천,1988,1,1
3,1988-01-01,-3.1,-1.0,-8.6,0.4,79.0,철원,1988,1,1
4,1988-01-01,3.7,6.5,0.1,0.0,57.0,속초,1988,1,1

In [ ]:
df_grain=pd.read_csv('작물추천_min_max_추가_데이터타입변경(코코아,밀 추가).csv')
del df_grain['Unnamed: 0']
df_grain.head()

   temperature    rainfall  temp_min  temp_max label
0    20.879744  202.935536        18        28  rice
1    21.770462  226.655537        18        28  rice
2    23.004459  263.964248        18        28  rice
3    26.491096  242.864034        18        28  rice
4    20.130175  262.717340        18        28  rice

In [ ]:
df_grain['label'].value_counts()

wheat          101
cocoa          101
muskmelon      100
coffee         100
cotton         100
coconut        100
papaya         100
orange         100
apple          100
rice           100
maize          100
grapes         100
mango          100
banana         100
pomegranate    100
lentil         100
kidneybeans    100
chickpea       100
watermelon     100
Name: label, dtype: int64

In [ ]:
# 6개월치 데이터를 추합 return 습도 x
def predict_6m_proba(region, start_month, pred_year):
    df = pd.DataFrame()
    for mon in range(start_month, start_month+6):
        pred_data = OLS_model_predict(region, mon, pred_year)
        # print(pred_data)
        tmp_data =[]
        for data in pred_data :
            tmp_data.append(data[-1])
        # print(tmp_data)
        df_pred  = predict_crops_6m(tmp_data)
        df = pd.concat([df, df_pred])
    return df.groupby(df.index).mean().sort_values(by='확률', ascending=False)

def predict_crops_6m(data):
    tmp_grain = df_grain[['temperature', 'temp_max', 'temp_min',  'rainfall', 'label']]
    xgb = XGBClassifier(booster = 'gbtree', learning_rate = 0.01, n_estimators = 10)  
    labelencoder = LabelEncoder()
    target_lb = labelencoder.fit_transform(tmp_grain.label)
    scaler = MinMaxScaler()
    grain_data = tmp_grain[tmp_grain.columns[:-1]]

    grain_data= grain_data.append({'temperature' :  data[0], 'temp_max' : data[1], 'temp_min' : data[2], 'rainfall' : data[3]*30} , ignore_index=True)

    grain_mmx = scaler.fit_transform(grain_data)

    # display(grain_data.tail())
    # display(grain_mmx[:-1])
    # display(grain_mmx[-1])

    X_train, X_test, y_train, y_test = train_test_split(
        grain_mmx[:-1], target_lb, stratify=target_lb, test_size=0.2,
        random_state=2022
    )
    xgb.fit(X_train, y_train)

    # print(grain_mmx[-1])
    df_pred = pd.DataFrame(xgb.predict_proba(list(grain_mmx[-1])), columns=labelencoder.classes_).T
    df_pred.columns = ['확률']
    df_pred = df_pred.sort_values(by='확률',ascending=False)
    return_pred = df_pred
    return return_pred

def OLS_model_predict(region, month, pred_year):
    df_tmp_region = df_weather[df_weather['조사지역'] == region]
    df_weather_region = df_tmp_region.groupby(['조사지역', '관측일자']).mean()
    df_weather_region = df_weather_region.reset_index(drop=False)

    df_group_mean = df_weather_region.groupby(['연', '월']).mean()
    df_group_mean = df_group_mean.reset_index(drop=False)
    df_month_mean = df_group_mean[df_group_mean['월'] == month]

    for i in df_month_mean.index:
        df_tmp = df_weather_region.loc[(df_weather_region['연'] == df_month_mean.loc[i, '연']) & (df_weather_region['월'] == df_month_mean.loc[i, '월'])]
        temp_max = df_tmp['temp_max'].max()
        temp_min = df_tmp['temp_min'].min()
        df_month_mean.loc[i, 'temp_max'] = temp_max
        df_month_mean.loc[i, 'temp_min'] = temp_min

    pred_list = []
    for value in df_month_mean.columns[2: -1]:
        df_target = df_month_mean[value]
        X_train2 = pd.DataFrame(df_month_mean[['연']], columns = ['연'])
        y_train2 = df_target.values

        # import statsmodels.api as sm
        X_train = sm.add_constant(X_train2)
        model = sm.OLS(y_train2, X_train2).fit()
        pred_value = model.predict(pred_year)
        pred_list.append([value, float(pred_value)])

    # print(f'\t\t\t{region}의 {month}월 {pred_year}의 예측값:')
    # print(pred_list)
    return pred_list

In [ ]:
predict_6m_proba('서울', 3, 2022)

                   확률
wheat        0.065607
kidneybeans  0.057892
grapes       0.057516
lentil       0.057515
maize        0.057280
cocoa        0.054272
rice         0.050048
chickpea     0.050037
coconut      0.050015
pomegranate  0.050009
coffee       0.049998
banana       0.049991
cotton       0.049989
apple        0.049987
watermelon   0.049982
papaya       0.049968
mango        0.049965
muskmelon    0.049965
orange       0.049964

In [ ]:
df.groupby(df.index).mean().sort_values(by='확률', ascending=False).head(3)

             확률
cocoa  0.252553
wheat  0.180007
maize  0.173578

In [ ]:
for region in tqdm(df_weather['조사지역'].unique()) :
    print(f'{region}지역 추천 Top 3 작물')
    display(predict_6m_proba(region, 3, 2022).head(3))
    print('\n')

  0%|          | 0/73 [00:00<?, ?it/s]

서울지역 추천 Top 3 작물

             확률
cocoa  0.252553
wheat  0.180007
maize  0.173578

  1%|▏         | 1/73 [00:04<05:43,  4.77s/it]

관악산지역 추천 Top 3 작물

             확률
wheat  0.205366
rice   0.197775
cocoa  0.169566

  3%|▎         | 2/73 [00:09<05:19,  4.50s/it]

춘천지역 추천 Top 3 작물

             확률
cocoa  0.256804
wheat  0.254331
maize  0.199499

  4%|▍         | 3/73 [00:15<06:14,  5.35s/it]

철원지역 추천 Top 3 작물

                   확률
wheat        0.310365
cocoa        0.278495
kidneybeans  0.072059

  5%|▌         | 4/73 [00:22<06:50,  5.95s/it]

속초지역 추천 Top 3 작물

             확률
wheat  0.264874
cocoa  0.196778
maize  0.174520

  7%|▋         | 5/73 [00:31<08:00,  7.07s/it]

원주지역 추천 Top 3 작물

             확률
wheat  0.279594
cocoa  0.254787
maize  0.172975

  8%|▊         | 6/73 [00:36<07:05,  6.36s/it]

대관령지역 추천 Top 3 작물

             확률
wheat  0.355426
maize  0.303502
rice   0.190997

 10%|▉         | 7/73 [00:42<07:05,  6.45s/it]

태백지역 추천 Top 3 작물

             확률
wheat  0.391814
maize  0.201363
cocoa  0.190647

 11%|█         | 8/73 [00:49<06:56,  6.40s/it]

인제지역 추천 Top 3 작물

             확률
wheat  0.378621
rice   0.113482
cocoa  0.107870

 12%|█▏        | 9/73 [00:54<06:33,  6.16s/it]

홍천지역 추천 Top 3 작물

             확률
wheat  0.387507
rice   0.115400
maize  0.100162

 14%|█▎        | 10/73 [01:01<06:29,  6.18s/it]

대전지역 추천 Top 3 작물

             확률
wheat  0.274457
cocoa  0.249614
maize  0.202118

 15%|█▌        | 11/73 [01:05<05:56,  5.75s/it]

금산지역 추천 Top 3 작물

             확률
wheat  0.411507
cocoa  0.198925
maize  0.088426

 16%|█▋        | 12/73 [01:10<05:31,  5.43s/it]

부여지역 추천 Top 3 작물

             확률
wheat  0.306625
cocoa  0.252496
maize  0.172893

 18%|█▊        | 13/73 [01:15<05:14,  5.25s/it]

천안지역 추천 Top 3 작물

             확률
wheat  0.279672
cocoa  0.256170
maize  0.173019

 19%|█▉        | 14/73 [01:20<05:02,  5.13s/it]

보령지역 추천 Top 3 작물

             확률
wheat  0.244811
cocoa  0.237091
maize  0.180409

 21%|██        | 15/73 [01:25<04:51,  5.03s/it]

서산지역 추천 Top 3 작물

             확률
cocoa  0.345553
wheat  0.176436
maize  0.169111

 22%|██▏       | 16/73 [01:29<04:42,  4.96s/it]

청주지역 추천 Top 3 작물

             확률
wheat  0.253251
cocoa  0.253150
maize  0.199931

 23%|██▎       | 17/73 [01:34<04:33,  4.89s/it]

추풍령지역 추천 Top 3 작물

             확률
wheat  0.300752
cocoa  0.197802
maize  0.181165

 25%|██▍       | 18/73 [01:39<04:26,  4.84s/it]

보은지역 추천 Top 3 작물

             확률
wheat  0.411835
cocoa  0.151415
rice   0.099382

 26%|██▌       | 19/73 [01:43<04:18,  4.79s/it]

제천지역 추천 Top 3 작물

             확률
wheat  0.383725
rice   0.114433
cocoa  0.109909

 27%|██▋       | 20/73 [01:48<04:12,  4.76s/it]

인천지역 추천 Top 3 작물

             확률
wheat  0.246120
cocoa  0.237937
maize  0.182850

 29%|██▉       | 21/73 [01:53<04:06,  4.74s/it]

강화지역 추천 Top 3 작물

             확률
wheat  0.387600
cocoa  0.147813
rice   0.082930

 30%|███       | 22/73 [01:58<04:01,  4.73s/it]

수원지역 추천 Top 3 작물

             확률
cocoa  0.196313
wheat  0.182491
maize  0.175004

 32%|███▏      | 23/73 [02:02<03:55,  4.71s/it]

이천지역 추천 Top 3 작물

             확률
wheat  0.251580
cocoa  0.230143
maize  0.202451

 33%|███▎      | 24/73 [02:07<03:50,  4.71s/it]

양평지역 추천 Top 3 작물

             확률
wheat  0.279498
cocoa  0.249468
maize  0.180579

 34%|███▍      | 25/73 [02:12<03:45,  4.70s/it]

광주지역 추천 Top 3 작물

             확률
wheat  0.305688
maize  0.202736
cocoa  0.186003

 36%|███▌      | 26/73 [02:16<03:40,  4.69s/it]

장흥지역 추천 Top 3 작물

             확률
wheat  0.265147
cocoa  0.237940
maize  0.172234

 37%|███▋      | 27/73 [02:21<03:41,  4.83s/it]

목포지역 추천 Top 3 작물

               확률
coconut  0.275411
wheat    0.198932
maize    0.177455

 38%|███▊      | 28/73 [02:26<03:35,  4.78s/it]

해남지역 추천 Top 3 작물

             확률
wheat  0.268749
cocoa  0.238863
maize  0.179847

 40%|███▉      | 29/73 [02:31<03:28,  4.75s/it]

고흥지역 추천 Top 3 작물

             확률
wheat  0.264971
cocoa  0.236433
maize  0.172161

 41%|████      | 30/73 [02:36<03:23,  4.74s/it]

완도지역 추천 Top 3 작물

             확률
wheat  0.217213
rice   0.167795
maize  0.163743

 42%|████▏     | 31/73 [02:40<03:18,  4.72s/it]

여수지역 추천 Top 3 작물

               확률
coconut  0.339537
rice     0.171938
coffee   0.169481

 44%|████▍     | 32/73 [02:45<03:13,  4.71s/it]

전주지역 추천 Top 3 작물

             확률
wheat  0.312028
cocoa  0.251576
maize  0.201615

 45%|████▌     | 33/73 [02:50<03:08,  4.70s/it]

임실지역 추천 Top 3 작물

             확률
wheat  0.472299
rice   0.114610
cocoa  0.110094

 47%|████▋     | 34/73 [02:54<03:02,  4.69s/it]

군산지역 추천 Top 3 작물

             확률
wheat  0.184313
maize  0.183097
cocoa  0.144687

 48%|████▊     | 35/73 [02:59<02:58,  4.69s/it]

부안지역 추천 Top 3 작물

             확률
cocoa  0.253721
wheat  0.216632
maize  0.172878

 49%|████▉     | 36/73 [03:04<02:53,  4.69s/it]

정읍지역 추천 Top 3 작물

             확률
wheat  0.311913
cocoa  0.252224
maize  0.201635

 51%|█████     | 37/73 [03:08<02:48,  4.68s/it]

남원지역 추천 Top 3 작물

             확률
wheat  0.438806
cocoa  0.247064
maize  0.084257

 52%|█████▏    | 38/73 [03:13<02:43,  4.67s/it]

장수지역 추천 Top 3 작물

             확률
wheat  0.396625
maize  0.200114
cocoa  0.193040

 53%|█████▎    | 39/73 [03:18<02:38,  4.67s/it]

부산지역 추천 Top 3 작물

              확률
coffee  0.173681
rice    0.171108
cocoa   0.167360

 55%|█████▍    | 40/73 [03:22<02:34,  4.68s/it]

밀양지역 추천 Top 3 작물

             확률
wheat  0.316452
cocoa  0.192413
rice   0.071569

 56%|█████▌    | 41/73 [03:27<02:29,  4.67s/it]

창원지역 추천 Top 3 작물

               확률
wheat    0.258501
coconut  0.185433
maize    0.167883

 58%|█████▊    | 42/73 [03:32<02:25,  4.68s/it]

통영지역 추천 Top 3 작물

               확률
coconut  0.270319
wheat    0.222804
rice     0.170734

 59%|█████▉    | 43/73 [03:36<02:20,  4.68s/it]

거제지역 추천 Top 3 작물

             확률
wheat  0.267618
rice   0.187877
cocoa  0.141849

 60%|██████    | 44/73 [03:42<02:22,  4.93s/it]

진주지역 추천 Top 3 작물

             확률
wheat  0.472498
cocoa  0.243341
rice   0.076411

 62%|██████▏   | 45/73 [03:46<02:15,  4.84s/it]

산청지역 추천 Top 3 작물

             확률
wheat  0.314658
cocoa  0.278185
rice   0.085877

 63%|██████▎   | 46/73 [03:51<02:09,  4.80s/it]

남해지역 추천 Top 3 작물

             확률
wheat  0.264977
cocoa  0.232411
maize  0.172368

 64%|██████▍   | 47/73 [03:56<02:03,  4.77s/it]

거창지역 추천 Top 3 작물

             확률
wheat  0.441978
cocoa  0.149357
rice   0.099279

 66%|██████▌   | 48/73 [04:01<01:58,  4.74s/it]

합천지역 추천 Top 3 작물

             확률
wheat  0.320307
cocoa  0.191151
rice   0.072399

 67%|██████▋   | 49/73 [04:05<01:53,  4.72s/it]

울산지역 추천 Top 3 작물

             확률
wheat  0.309189
cocoa  0.250690
maize  0.205120

 68%|██████▊   | 50/73 [04:10<01:48,  4.70s/it]

제주지역 추천 Top 3 작물

                   확률
banana       0.228973
maize        0.177733
kidneybeans  0.175728

 70%|██████▉   | 51/73 [04:15<01:43,  4.70s/it]

고산지역 추천 Top 3 작물

                   확률
kidneybeans  0.206325
coconut      0.188705
papaya       0.176955

 71%|███████   | 52/73 [04:19<01:38,  4.69s/it]

서귀포지역 추천 Top 3 작물

               확률
rice     0.336096
coffee   0.200405
coconut  0.167023

 73%|███████▎  | 53/73 [04:24<01:33,  4.68s/it]

대구지역 추천 Top 3 작물

              확률
wheat   0.260570
cocoa   0.202303
lentil  0.073499

 74%|███████▍  | 54/73 [04:29<01:28,  4.67s/it]

구미지역 추천 Top 3 작물

              확률
wheat   0.263113
cocoa   0.191159
lentil  0.074344

 75%|███████▌  | 55/73 [04:33<01:24,  4.67s/it]

문경지역 추천 Top 3 작물

             확률
wheat  0.273303
maize  0.221620
cocoa  0.149443

 77%|███████▋  | 56/73 [04:38<01:19,  4.68s/it]

영주지역 추천 Top 3 작물

             확률
wheat  0.313325
maize  0.221040
rice   0.114645

 78%|███████▊  | 57/73 [04:42<01:14,  4.66s/it]

봉화지역 추천 Top 3 작물

             확률
wheat  0.382749
cocoa  0.151008
rice   0.092582

 79%|███████▉  | 58/73 [04:47<01:09,  4.63s/it]

안동지역 추천 Top 3 작물

             확률
cocoa  0.253405
wheat  0.253291
maize  0.199504

 81%|████████  | 59/73 [04:52<01:04,  4.64s/it]

영덕지역 추천 Top 3 작물

             확률
wheat  0.262931
cocoa  0.249943
rice   0.072985

 82%|████████▏ | 60/73 [04:56<01:00,  4.65s/it]

울진지역 추천 Top 3 작물

             확률
wheat  0.316210
cocoa  0.208684
maize  0.203125

 84%|████████▎ | 61/73 [05:01<00:55,  4.66s/it]

의성지역 추천 Top 3 작물

              확률
wheat   0.421196
rice    0.103632
lentil  0.072992

 85%|████████▍ | 62/73 [05:06<00:51,  4.70s/it]

영천지역 추천 Top 3 작물

             확률
wheat  0.268095
cocoa  0.190615
maize  0.073791

 86%|████████▋ | 63/73 [05:11<00:47,  4.72s/it]

포항지역 추천 Top 3 작물

               확률
wheat    0.319658
coconut  0.183348
cocoa    0.137461

 88%|████████▊ | 64/73 [05:15<00:42,  4.74s/it]

울릉도지역 추천 Top 3 작물

                   확률
cocoa        0.333348
wheat        0.272166
kidneybeans  0.176887

 89%|████████▉ | 65/73 [05:20<00:37,  4.73s/it]

동해지역 추천 Top 3 작물

             확률
wheat  0.341935
cocoa  0.198751
maize  0.174514

 90%|█████████ | 66/73 [05:25<00:32,  4.71s/it]

영월지역 추천 Top 3 작물

             확률
wheat  0.389324
rice   0.100693
cocoa  0.094071

 92%|█████████▏| 67/73 [05:29<00:27,  4.66s/it]

흑산도지역 추천 Top 3 작물

               확률
coconut  0.201564
wheat    0.094537
grapes   0.084075

 93%|█████████▎| 68/73 [05:34<00:23,  4.63s/it]

동두천지역 추천 Top 3 작물

             확률
wheat  0.254451
cocoa  0.226546
maize  0.202497

 95%|█████████▍| 69/73 [05:38<00:18,  4.59s/it]

문산지역 추천 Top 3 작물

             확률
cocoa  0.224886
wheat  0.191440
maize  0.174074

 96%|█████████▌| 70/73 [05:43<00:13,  4.57s/it]

진도지역 추천 Top 3 작물

              확률
cocoa   0.334328
wheat   0.229759
grapes  0.086227

 97%|█████████▋| 71/73 [05:47<00:09,  4.57s/it]

상주지역 추천 Top 3 작물

             확률
cocoa  0.301050
wheat  0.254634
rice   0.071254

 99%|█████████▊| 72/73 [05:52<00:04,  4.56s/it]

고창지역 추천 Top 3 작물

             확률
wheat  0.282840
cocoa  0.183927
maize  0.170499

100%|██████████| 73/73 [05:57<00:00,  4.89s/it]

### 모든지역 데이터를 한개의 df로 리턴해주는 함수

In [ ]:
# 모든지역 데이터 return
def predict_6m_all_region(start_month, pred_year):
    df = pd.DataFrame()
    for mon in range(start_month, start_month+6):
        region_data = []
        for region in df_weather['조사지역'].unique():
            pred_data = OLS_model_predict(region, mon, pred_year)
            tmp_data =[]
            for data in pred_data :
                tmp_data.append(data[-1])
            tmp_data.append(region)
            region_data.append(tmp_data)

        # print(tmp_data)
        df_pred  = predict_crops_6m(region_data)
        df = pd.concat([df, df_pred])
        df_gr = df.groupby(df.index).mean()
        for col in df_gr.columns :
            df_gr = df_gr.sort_values(by=col, ascending=False)
        
    return df_gr

def predict_crops_6m(data):
    tmp_grain = df_grain[['temperature', 'temp_max', 'temp_min',  'rainfall', 'label']]
    xgb = XGBClassifier(booster = 'gbtree', learning_rate = 0.01, n_estimators = 10)  
    labelencoder = LabelEncoder()
    target_lb = labelencoder.fit_transform(tmp_grain.label)
    scaler = MinMaxScaler()
    grain_data = tmp_grain[tmp_grain.columns[:-1]]

    for value in data:
        grain_data= grain_data.append({'temperature' :  value[0], 'temp_max' : value[1], 'temp_min' : value[2], 'rainfall' : value[3]*30} , ignore_index=True)

    grain_mmx = scaler.fit_transform(grain_data)

    # display(grain_data.tail())
    # display(grain_mmx[:-1])
    # display(grain_mmx[-1])

    X_train, X_test, y_train, y_test = train_test_split(
        grain_mmx[:-len(data)], target_lb, stratify=target_lb, test_size=0.2,
        random_state=2022
    )
    xgb.fit(X_train, y_train)

    # print(grain_mmx[-1])
    return_pred = pd.DataFrame()
    for i, value in enumerate(data):
        df_pred = pd.DataFrame(xgb.predict_proba(list(grain_mmx[-(len(data)-i)])), columns=labelencoder.classes_).T
        df_pred.columns = [value[4]]
        # df_pred = df_pred.sort_values(by='확률',ascending=False)
        return_pred = pd.concat([return_pred, df_pred], axis=1)
    return return_pred

def OLS_model_predict(region, month, pred_year):
    df_tmp_region = df_weather[df_weather['조사지역'] == region]
    df_weather_region = df_tmp_region.groupby(['조사지역', '관측일자']).mean()
    df_weather_region = df_weather_region.reset_index(drop=False)

    df_group_mean = df_weather_region.groupby(['연', '월']).mean()
    df_group_mean = df_group_mean.reset_index(drop=False)
    df_month_mean = df_group_mean[df_group_mean['월'] == month]

    for i in df_month_mean.index:
        df_tmp = df_weather_region.loc[(df_weather_region['연'] == df_month_mean.loc[i, '연']) & (df_weather_region['월'] == df_month_mean.loc[i, '월'])]
        temp_max = df_tmp['temp_max'].max()
        temp_min = df_tmp['temp_min'].min()
        df_month_mean.loc[i, 'temp_max'] = temp_max
        df_month_mean.loc[i, 'temp_min'] = temp_min

    pred_list = []
    for value in df_month_mean.columns[2: -2]:
        df_target = df_month_mean[value]
        X_train2 = pd.DataFrame(df_month_mean[['연']], columns = ['연'])
        y_train2 = df_target.values

        # import statsmodels.api as sm
        X_train = sm.add_constant(X_train2)
        model = sm.OLS(y_train2, X_train2).fit()
        pred_value = model.predict(pred_year)
        pred_list.append([region, float(pred_value)])

    # print(f'\t\t\t{region}의 {month}월 {pred_year}의 예측값:')
    # print(pred_list)
    return pred_list

In [ ]:
%time predict_6m_all_region(4, 2100)

CPU times: user 1min, sys: 785 ms, total: 1min
Wall time: 1min

,서울,관악산,춘천,철원,속초,원주,대관령,태백,인제,홍천,...,포항,울릉도,동해,영월,흑산도,동두천,문산,진도,상주,고창
cocoa,0.059480,0.054247,0.059933,0.059924,0.064017,0.059718,0.050513,0.062386,0.059332,0.059093,...,0.058667,0.060303,0.059578,0.059094,0.055828,0.059963,0.055870,0.055468,0.059718,0.059311
coconut,0.058855,0.050008,0.051418,0.051385,0.051197,0.051202,0.050559,0.049587,0.051002,0.050778,...,0.066332,0.051769,0.051040,0.050779,0.059854,0.051438,0.051611,0.051260,0.051186,0.059063
wheat,0.059290,0.057948,0.059407,0.059737,0.059201,0.059191,0.075301,0.065584,0.067205,0.066967,...,0.058141,0.060118,0.059045,0.066968,0.051507,0.059426,0.059963,0.059168,0.059192,0.058774
maize,0.050929,0.064160,0.058687,0.058645,0.058083,0.058471,0.057832,0.063402,0.057915,0.058071,...,0.057407,0.051769,0.065183,0.058072,0.051558,0.058322,0.058871,0.058460,0.058471,0.057656
pomegranate,0.050912,0.049991,0.051400,0.051407,0.051170,0.055311,0.050590,0.049617,0.050998,0.054887,...,0.057961,0.051743,0.051013,0.054887,0.051534,0.051419,0.051609,0.051188,0.055311,0.054894
rice,0.050967,0.066305,0.051435,0.051417,0.051269,0.051218,0.058488,0.057571,0.051034,0.050795,...,0.050203,0.051720,0.051113,0.050795,0.051588,0.051455,0.051643,0.051247,0.051218,0.050799
banana,0.058830,0.049960,0.051388,0.051361,0.051173,0.051172,0.050501,0.049530,0.050988,0.050749,...,0.050191,0.051726,0.051016,0.050749,0.051515,0.051408,0.051597,0.051181,0.051172,0.050791
chickpea,0.050940,0.050043,0.051428,0.051411,0.051248,0.051187,0.050646,0.049622,0.051026,0.050788,...,0.050137,0.051824,0.051091,0.050788,0.051587,0.051448,0.051637,0.051267,0.051212,0.050770
cotton,0.050907,0.049972,0.051371,0.051354,0.051165,0.051155,0.050536,0.049539,0.050970,0.050732,...,0.050092,0.051749,0.051009,0.050720,0.051547,0.051391,0.051580,0.051193,0.051143,0.050738
papaya,0.050891,0.049948,0.051356,0.051338,0.051150,0.051140,0.050499,0.049527,0.050955,0.050716,...,0.050089,0.051723,0.050994,0.050717,0.051512,0.051375,0.051564,0.051168,0.051140,0.050723
kidneybeans,0.050891,0.057858,0.051355,0.051338,0.051149,0.051139,0.050512,0.057438,0.050955,0.050716,...,0.050089,0.051737,0.050993,0.050716,0.059838,0.051375,0.051564,0.059078,0.051139,0.050722
watermelon,0.050890,0.049947,0.051355,0.051337,0.051149,0.051139,0.050498,0.049526,0.050954,0.050715,...,0.050088,0.051722,0.050993,0.050716,0.051511,0.051374,0.051563,0.051167,0.051139,0.050722
lentil,0.050890,0.049946,0.051354,0.051337,0.051149,0.051138,0.050497,0.049526,0.050954,0.050715,...,0.050088,0.051721,0.050992,0.050716,0.051510,0.051374,0.051563,0.051167,0.051138,0.050721
coffee,0.050889,0.049946,0.051354,0.051336,0.051148,0.051138,0.050531,0.049525,0.050953,0.050714,...,0.050087,0.051755,0.050992,0.050715,0.051546,0.051373,0.051562,0.051166,0.051138,0.050721
apple,0.050889,0.049946,0.051354,0.051336,0.051148,0.051138,0.050519,0.049525,0.050953,0.050714,...,0.050087,0.051744,0.050992,0.050715,0.051534,0.051373,0.051562,0.051166,0.051138,0.050721
mango,0.050888,0.049945,0.051352,0.051335,0.051147,0.051137,0.050495,0.049524,0.050952,0.050713,...,0.050086,0.051720,0.050990,0.050714,0.051509,0.051372,0.051561,0.051165,0.051137,0.050719
muskmelon,0.050887,0.049944,0.051352,0.051334,0.051146,0.051136,0.050495,0.049524,0.050951,0.050713,...,0.050085,0.051719,0.050990,0.050713,0.051508,0.051371,0.051560,0.051164,0.051136,0.050719
orange,0.050887,0.049943,0.051351,0.051334,0.051146,0.051135,0.050494,0.049523,0.050951,0.050712,...,0.050085,0.051719,0.050989,0.050713,0.051507,0.051371,0.051560,0.051164,0.051136,0.050718
grapes,0.050887,0.049943,0.051351,0.051334,0.051146,0.051135,0.050494,0.049523,0.050951,0.050712,...,0.050085,0.051719,0.050989,0.050713,0.051507,0.051371,0.051560,0.051164,0.051136,0.050718

### xgbooster best_params 추출
- 시계열 데이터의 특성을 고려하여 해당월의 classifier를 다 따로 돌림

In [ ]:
# OLS_model_predict(region, month, pred_year):
region = '서울'
month = 6
pred_year = 2022

df_tmp_region = df_weather[df_weather['조사지역'] == region]
df_weather_region = df_tmp_region.groupby(['조사지역', '관측일자']).mean()
df_weather_region = df_weather_region.reset_index(drop=False)

df_group_mean = df_weather_region.groupby(['연', '월']).mean()
df_group_mean = df_group_mean.reset_index(drop=False)
df_month_mean = df_group_mean[df_group_mean['월'] == month]

for i in df_month_mean.index:
    df_tmp = df_weather_region.loc[(df_weather_region['연'] == df_month_mean.loc[i, '연']) & (df_weather_region['월'] == df_month_mean.loc[i, '월'])]
    temp_max = df_tmp['temp_max'].max()
    temp_min = df_tmp['temp_min'].min()
    df_month_mean.loc[i, 'temp_max'] = temp_max
    df_month_mean.loc[i, 'temp_min'] = temp_min

pred_list = []
for value in df_month_mean.columns[2: -1]:
    df_target = df_month_mean[value]
    X_train2 = pd.DataFrame(df_month_mean[['연']], columns = ['연'])
    y_train2 = df_target.values

    # import statsmodels.api as sm
    X_train = sm.add_constant(X_train2)
    model = sm.OLS(y_train2, X_train2).fit()
    pred_value = model.predict(pred_year)
    pred_list.append([value, float(pred_value)])

# print(f'\t\t\t{region}의 {month}월 {pred_year}의 예측값:')
# print(pred_list)
pred_list

[['temperature', 22.80263004569429],
 ['temp_max', 32.66101643862828],
 ['temp_min', 14.510903067907272],
 ['rainfall', 4.682851271821746],
 ['humidity', 67.1027178427563]]

In [ ]:
from sklearn.model_selection import GridSearchCV
XGBClassifier().get_params()

{'base_score': 0.5,
 'booster': 'gbtree',
 'colsample_bylevel': 1,
 'colsample_bynode': 1,
 'colsample_bytree': 1,
 'gamma': 0,
 'learning_rate': 0.1,
 'max_delta_step': 0,
 'max_depth': 3,
 'min_child_weight': 1,
 'missing': None,
 'n_estimators': 100,
 'n_jobs': 1,
 'nthread': None,
 'objective': 'binary:logistic',
 'random_state': 0,
 'reg_alpha': 0,
 'reg_lambda': 1,
 'scale_pos_weight': 1,
 'seed': None,
 'silent': None,
 'subsample': 1,
 'verbosity': 1}

In [ ]:
pred_data = pred_list
tmp_data =[]
for data in pred_data :
    tmp_data.append(data[-1])

data = tmp_data
tmp_grain = df_grain[['temperature', 'temp_max', 'temp_min',  'rainfall', 'label']]



labelencoder = LabelEncoder()
target_lb = labelencoder.fit_transform(tmp_grain.label)
scaler = MinMaxScaler()
grain_data = tmp_grain[tmp_grain.columns[:-1]]

grain_data= grain_data.append({'temperature' :  data[0], 'temp_max' : data[1], 'temp_min' : data[2], 'rainfall' : data[3]*30} , ignore_index=True)

grain_mmx = scaler.fit_transform(grain_data)

# display(grain_data.tail())
# display(grain_mmx[:-1])
# display(grain_mmx[-1])

X_train, X_test, y_train, y_test = train_test_split(
    grain_mmx[:-1], target_lb, stratify=target_lb, test_size=0.2,
    random_state=2022
)

xgb = XGBClassifier()  
params = {
    'booster' : ['gbtree', 'gblinear'],
    'n_estimators' : [10, 100, 1000],
    'learning_rate' : [0.01, 0.05, 0.1]
}

xgb_grid = GridSearchCV(
    xgb, params, scoring='accuracy', cv=5
)


xgb_grid.fit(X_train, y_train)

print(xgb_grid.best_score_, xgb_grid.best_params_)
xgb_best = xgb_grid.best_estimator_

# print(grain_mmx[-1])
df_pred = pd.DataFrame(xgb_best.predict_proba(list(grain_mmx[-1])), columns=labelencoder.classes_).T
df_pred.columns = ['확률']
df_pred = df_pred.sort_values(by='확률',ascending=False)
return_pred = df_pred
return_pred

0.9953968938740294 {'booster': 'gbtree', 'learning_rate': 0.01, 'n_estimators': 10}

                   확률
cocoa        0.076987
coconut      0.051366
cotton       0.051278
banana       0.051278
maize        0.051278
papaya       0.051275
kidneybeans  0.051274
watermelon   0.051274
chickpea     0.051274
lentil       0.051273
apple        0.051273
coffee       0.051273
rice         0.051272
mango        0.051272
pomegranate  0.051272
muskmelon    0.051271
orange       0.051271
grapes       0.051271
wheat        0.051270

In [ ]:
# xgbooster GridSearch 샘플 10개만 (너무 오래 걸림)
def xgboost_best_params(start_month, pred_year):
    sample_list = np.random.choice(72, 10)
    df = pd.DataFrame()
    for mon in range(start_month, start_month+6):
        region_data = []
        for region in df_weather['조사지역'].unique()[sample_list]:
            pred_data = OLS_model_predict(region, mon, pred_year)
            tmp_data =[]
            for data in pred_data :
                tmp_data.append(data[-1])
            tmp_data.append(region)
            region_data.append(tmp_data)

        # print(tmp_data)
        df_pred  = xgboost_params(region_data)
        df = pd.concat([df, df_pred])
        df_gr = df.groupby(df.index).mean()
        for col in df_gr.columns :
            df_gr = df_gr.sort_values(by=col, ascending=False)
        
    return df_gr

def xgboost_params(data):
    tmp_grain = df_grain[['temperature', 'temp_max', 'temp_min',  'rainfall', 'label']]

    labelencoder = LabelEncoder()
    target_lb = labelencoder.fit_transform(tmp_grain.label)
    scaler = MinMaxScaler()
    grain_data = tmp_grain[tmp_grain.columns[:-1]]

    for value in data:
        grain_data= grain_data.append({'temperature' :  value[0], 'temp_max' : value[1], 'temp_min' : value[2], 'rainfall' : value[3]*30} , ignore_index=True)

    grain_mmx = scaler.fit_transform(grain_data)

    # display(grain_data.tail())
    # display(grain_mmx[:-1])
    # display(grain_mmx[-1])

    X_train, X_test, y_train, y_test = train_test_split(
        grain_mmx[:-len(data)], target_lb, stratify=target_lb, test_size=0.2,
        random_state=2022
    )


    xgb = XGBClassifier()  
    params = {
        'booster' : ['gbtree', 'gblinear'],
        'n_estimators' : [10, 100, 1000],
        'learning_rate' : [0.01, 0.05, 0.1]
    }

    xgb_grid = GridSearchCV(
        xgb, params, scoring='accuracy', cv=5
    )

    xgb_grid.fit(X_train, y_train)

    print(xgb_grid.best_score_, xgb_grid.best_params_)
    xgb_best = xgb_grid.best_estimator_

    # print(grain_mmx[-1])
    return_pred = pd.DataFrame()
    for i, value in enumerate(data):
        df_pred = pd.DataFrame(xgb_best.predict_proba(list(grain_mmx[-(len(data)-i)])), columns=labelencoder.classes_).T
        df_pred.columns = [value[4]]
        # df_pred = df_pred.sort_values(by='확률',ascending=False)
        return_pred = pd.concat([return_pred, df_pred], axis=1)
    return return_pred

def OLS_model_predict(region, month, pred_year):
    df_tmp_region = df_weather[df_weather['조사지역'] == region]
    df_weather_region = df_tmp_region.groupby(['조사지역', '관측일자']).mean()
    df_weather_region = df_weather_region.reset_index(drop=False)

    df_group_mean = df_weather_region.groupby(['연', '월']).mean()
    df_group_mean = df_group_mean.reset_index(drop=False)
    df_month_mean = df_group_mean[df_group_mean['월'] == month]

    for i in df_month_mean.index:
        df_tmp = df_weather_region.loc[(df_weather_region['연'] == df_month_mean.loc[i, '연']) & (df_weather_region['월'] == df_month_mean.loc[i, '월'])]
        temp_max = df_tmp['temp_max'].max()
        temp_min = df_tmp['temp_min'].min()
        df_month_mean.loc[i, 'temp_max'] = temp_max
        df_month_mean.loc[i, 'temp_min'] = temp_min

    pred_list = []
    for value in df_month_mean.columns[2: -2]:
        df_target = df_month_mean[value]
        X_train2 = pd.DataFrame(df_month_mean[['연']], columns = ['연'])
        y_train2 = df_target.values

        # import statsmodels.api as sm
        X_train = sm.add_constant(X_train2)
        model = sm.OLS(y_train2, X_train2).fit()
        pred_value = model.predict(pred_year)
        pred_list.append([region, float(pred_value)])

    # print(f'\t\t\t{region}의 {month}월 {pred_year}의 예측값:')
    # print(pred_list)
    return pred_list

In [ ]:
xgboost_best_params(3, 2022)

0.9953968938740294 {'booster': 'gbtree', 'learning_rate': 0.01, 'n_estimators': 10}
0.9953968938740294 {'booster': 'gbtree', 'learning_rate': 0.01, 'n_estimators': 10}
0.9953968938740294 {'booster': 'gbtree', 'learning_rate': 0.01, 'n_estimators': 10}
0.9953968938740294 {'booster': 'gbtree', 'learning_rate': 0.01, 'n_estimators': 10}
0.9953968938740294 {'booster': 'gbtree', 'learning_rate': 0.01, 'n_estimators': 10}
0.9953968938740294 {'booster': 'gbtree', 'learning_rate': 0.01, 'n_estimators': 10}

,부안,속초,장수,안동,보령,완도,전주,장흥,울산,고산
coconut,0.050373,0.050752,0.049754,0.050409,0.050406,0.057320,0.050818,0.050766,0.050820,0.059031
kidneybeans,0.058251,0.050734,0.057633,0.050391,0.050386,0.049371,0.050785,0.058645,0.050787,0.058960
wheat,0.066327,0.067120,0.074164,0.066429,0.066392,0.065633,0.067222,0.067120,0.067225,0.058618
grapes,0.050322,0.058626,0.049704,0.050373,0.057906,0.057250,0.050767,0.050716,0.050769,0.058527
papaya,0.050326,0.050721,0.049708,0.050378,0.050359,0.049344,0.050772,0.050720,0.050774,0.055723
chickpea,0.050396,0.050817,0.049803,0.050448,0.050429,0.049415,0.050843,0.050791,0.050845,0.050719
maize,0.057638,0.058033,0.063938,0.064586,0.057670,0.056656,0.064981,0.058033,0.064984,0.050691
coffee,0.050357,0.050752,0.049741,0.050409,0.050423,0.051522,0.050804,0.050752,0.050806,0.050688
cocoa,0.054630,0.055024,0.058286,0.054682,0.054658,0.053642,0.055075,0.055022,0.055077,0.050676
pomegranate,0.050392,0.050788,0.049774,0.050444,0.050425,0.049387,0.050839,0.050787,0.050817,0.050665
cotton,0.050347,0.050745,0.049742,0.050402,0.050393,0.049377,0.050796,0.050741,0.050798,0.050665
apple,0.050346,0.050740,0.049729,0.050397,0.050401,0.049386,0.050792,0.050741,0.050794,0.050665
rice,0.050406,0.050800,0.049785,0.050457,0.050437,0.057731,0.050851,0.050839,0.050853,0.050658
banana,0.050349,0.050743,0.049711,0.050400,0.050372,0.057262,0.050794,0.050742,0.050796,0.050624
watermelon,0.050341,0.050735,0.049707,0.050392,0.050372,0.049343,0.050787,0.050719,0.050773,0.050620
lentil,0.058232,0.050719,0.049707,0.058283,0.057906,0.049342,0.050770,0.050718,0.050772,0.050619
mango,0.050323,0.050717,0.049705,0.050374,0.050356,0.049340,0.050768,0.050717,0.050770,0.050618
muskmelon,0.050322,0.050717,0.049704,0.050374,0.050355,0.049340,0.050768,0.050716,0.050770,0.050617
orange,0.050322,0.050716,0.049704,0.050373,0.050355,0.049339,0.050767,0.050716,0.050769,0.050617

### LGBMClassifier 사용

In [ ]:
# lgbm GridSearch 샘플 10개만 (너무 오래 걸림)
def lgbm_best_params(start_month, pred_year):
    sample_list = np.random.choice(72, 10)
    df = pd.DataFrame()
    for mon in range(start_month, start_month+6):
        region_data = []
        for region in df_weather['조사지역'].unique()[sample_list]:
            pred_data = OLS_model_predict(region, mon, pred_year)
            tmp_data =[]
            for data in pred_data :
                tmp_data.append(data[-1])
            tmp_data.append(region)
            region_data.append(tmp_data)

        # print(tmp_data)
        df_pred  = lgbm_params(region_data)
        df = pd.concat([df, df_pred])
        df_gr = df.groupby(df.index).mean()
        for col in df_gr.columns :
            df_gr = df_gr.sort_values(by=col, ascending=False)
        
    return df_gr

def lgbm_params(data):
    tmp_grain = df_grain[['temperature', 'temp_max', 'temp_min',  'rainfall', 'label']]

    labelencoder = LabelEncoder()
    target_lb = labelencoder.fit_transform(tmp_grain.label)
    scaler = MinMaxScaler()
    grain_data = tmp_grain[tmp_grain.columns[:-1]]

    for value in data:
        grain_data= grain_data.append({'temperature' :  value[0], 'temp_max' : value[1], 'temp_min' : value[2], 'rainfall' : value[3]*30} , ignore_index=True)

    grain_mmx = scaler.fit_transform(grain_data)

    # display(grain_data.tail())
    # display(grain_mmx[:-1])
    # display(grain_mmx[-1])

    X_train, X_test, y_train, y_test = train_test_split(
        grain_mmx[:-len(data)], target_lb, stratify=target_lb, test_size=0.2,
        random_state=2022
    )


    lgb = LGBMClassifier() 
    params = {
        # 'boosting ' : ['gbdt', 'rf'],
        'n_estimators' : [100, 1000, 1000],
        'learning_rate' : [0.01, 0.05],
        'num_iteration ' : [5, 10, 50]
    }

    lgb_grid = GridSearchCV(
        lgb, params, scoring='accuracy', cv=5
    )



    evals = [(X_test, y_test)]
    lgb_grid.fit(X_train, y_train, eval_set=evals, eval_metric='logloss', verbose=False)

    print(lgb_grid.best_score_, lgb_grid.best_params_)
    lgb_best = lgb_grid.best_estimator_

    # print(grain_mmx[-1])
    return_pred = pd.DataFrame()
    for i, value in enumerate(data):
        df_pred = pd.DataFrame(lgb_best.predict_proba(list(grain_mmx[-(len(data)-i)])), columns=labelencoder.classes_).T
        df_pred.columns = [value[4]]
        # df_pred = df_pred.sort_values(by='확률',ascending=False)
        return_pred = pd.concat([return_pred, df_pred], axis=1)
    return return_pred

def OLS_model_predict(region, month, pred_year):
    df_tmp_region = df_weather[df_weather['조사지역'] == region]
    df_weather_region = df_tmp_region.groupby(['조사지역', '관측일자']).mean()
    df_weather_region = df_weather_region.reset_index(drop=False)

    df_group_mean = df_weather_region.groupby(['연', '월']).mean()
    df_group_mean = df_group_mean.reset_index(drop=False)
    df_month_mean = df_group_mean[df_group_mean['월'] == month]

    for i in df_month_mean.index:
        df_tmp = df_weather_region.loc[(df_weather_region['연'] == df_month_mean.loc[i, '연']) & (df_weather_region['월'] == df_month_mean.loc[i, '월'])]
        temp_max = df_tmp['temp_max'].max()
        temp_min = df_tmp['temp_min'].min()
        df_month_mean.loc[i, 'temp_max'] = temp_max
        df_month_mean.loc[i, 'temp_min'] = temp_min

    pred_list = []
    for value in df_month_mean.columns[2: -2]:
        df_target = df_month_mean[value]
        X_train2 = pd.DataFrame(df_month_mean[['연']], columns = ['연'])
        y_train2 = df_target.values

        # import statsmodels.api as sm
        X_train = sm.add_constant(X_train2)
        model = sm.OLS(y_train2, X_train2).fit()
        pred_value = model.predict(pred_year)
        pred_list.append([region, float(pred_value)])

    # print(f'\t\t\t{region}의 {month}월 {pred_year}의 예측값:')
    # print(pred_list)
    return pred_list

In [ ]:
lgbm_best_params(4, 2022)

0.9980263157894737 {'learning_rate': 0.01, 'n_estimators': 1000, 'num_iteration ': 5}

ValueError: ignored

In [ ]:
# 모든지역 데이터 return
def predict_6m_all_region_lgb(start_month, pred_year):
    df = pd.DataFrame()
    for mon in range(start_month, start_month+6):
        region_data = []
        for region in df_weather['조사지역'].unique():
            pred_data = OLS_model_predict(region, mon, pred_year)
            tmp_data =[]
            for data in pred_data :
                tmp_data.append(data[-1])
            tmp_data.append(region)
            region_data.append(tmp_data)

        # print(tmp_data)
        df_pred  = predict_crops_6m(region_data)
        df = pd.concat([df, df_pred])
        df_gr = df.groupby(df.index).mean()
        for col in df_gr.columns :
            df_gr = df_gr.sort_values(by=col, ascending=False)
        
    return df_gr

def predict_crops_6m_lgb(data):
    tmp_grain = df_grain[['temperature', 'temp_max', 'temp_min',  'rainfall', 'label']]

    labelencoder = LabelEncoder()
    target_lb = labelencoder.fit_transform(tmp_grain.label)
    scaler = MinMaxScaler()
    grain_data = tmp_grain[tmp_grain.columns[:-1]]

    for value in data:
        grain_data= grain_data.append({'temperature' :  value[0], 'temp_max' : value[1], 'temp_min' : value[2], 'rainfall' : value[3]*30} , ignore_index=True)

    grain_mmx = scaler.fit_transform(grain_data)

    # display(grain_data.tail())
    # display(grain_mmx[:-1])
    # display(grain_mmx[-1])

    X_train, X_test, y_train, y_test = train_test_split(
        grain_mmx[:-len(data)], target_lb, stratify=target_lb, test_size=0.2,
        random_state=2022
    )

    lgb = LGBMClassifier(learning_rate = 0.01, n_estimators = 1000, num_iteration = 5) 

    evals = [(X_test, y_test)]
    lgb.fit(X_train, y_train, eval_set=evals, eval_metric='logloss', verbose=False)


    # print(grain_mmx[-1])
    return_pred = pd.DataFrame()
    for i, value in enumerate(data):
        df_pred = pd.DataFrame(lgb.predict_proba(list(grain_mmx[-(len(data)-i)])), columns=labelencoder.classes_).T
        df_pred.columns = [value[4]]
        # df_pred = df_pred.sort_values(by='확률',ascending=False)
        return_pred = pd.concat([return_pred, df_pred], axis=1)
    return return_pred

def OLS_model_predict(region, month, pred_year):
    df_tmp_region = df_weather[df_weather['조사지역'] == region]
    df_weather_region = df_tmp_region.groupby(['조사지역', '관측일자']).mean()
    df_weather_region = df_weather_region.reset_index(drop=False)

    df_group_mean = df_weather_region.groupby(['연', '월']).mean()
    df_group_mean = df_group_mean.reset_index(drop=False)
    df_month_mean = df_group_mean[df_group_mean['월'] == month]

    for i in df_month_mean.index:
        df_tmp = df_weather_region.loc[(df_weather_region['연'] == df_month_mean.loc[i, '연']) & (df_weather_region['월'] == df_month_mean.loc[i, '월'])]
        temp_max = df_tmp['temp_max'].max()
        temp_min = df_tmp['temp_min'].min()
        df_month_mean.loc[i, 'temp_max'] = temp_max
        df_month_mean.loc[i, 'temp_min'] = temp_min

    pred_list = []
    for value in df_month_mean.columns[2: -2]:
        df_target = df_month_mean[value]
        X_train2 = pd.DataFrame(df_month_mean[['연']], columns = ['연'])
        y_train2 = df_target.values

        # import statsmodels.api as sm
        X_train = sm.add_constant(X_train2)
        model = sm.OLS(y_train2, X_train2).fit()
        pred_value = model.predict(pred_year)
        pred_list.append([region, float(pred_value)])

    # print(f'\t\t\t{region}의 {month}월 {pred_year}의 예측값:')
    # print(pred_list)
    return pred_list

In [ ]:
%time df = predict_6m_all_region_lgb(3, 2100)
for col in df.columns:
    df = df.sort_values(by=col, ascending=False)
    print(col, '\n', df[col].head(3))

CPU times: user 1min 3s, sys: 441 ms, total: 1min 3s
Wall time: 1min 4s
서울
 wheat      0.066671
coconut    0.058220
banana     0.058210
Name: 서울, dtype: float32
관악산
 wheat          0.065890
rice           0.058279
kidneybeans    0.057813
Name: 관악산, dtype: float32
춘천
 wheat     0.066810
lentil    0.058663
maize     0.057711
Name: 춘천, dtype: float32
철원
 wheat     0.06640
grapes    0.05791
lentil    0.05791
Name: 철원, dtype: float32
속초
 wheat    0.067379
cocoa    0.059515
maize    0.057883
Name: 속초, dtype: float32
원주
 wheat     0.066593
lentil    0.058446
maize     0.057494
Name: 원주, dtype: float32
대관령
 wheat     0.075296
grapes    0.058402
maize     0.057829
Name: 대관령, dtype: float32
태백
 wheat          0.073527
cocoa          0.062328
kidneybeans    0.057393
Name: 태백, dtype: float32
인제
 wheat     0.074589
lentil    0.058243
maize     0.057305
Name: 인제, dtype: float32
홍천
 wheat     0.074350
lentil    0.058004
maize     0.057460
Name: 홍천, dtype: float32
대전
 wheat      0.067166
coconut    0.059057
maize      0.057670
Name: 대전, dtype: float32
금산
 wheat    0.075360
maize    0.058073
cocoa    0.054806
Name: 금산, dtype: float32
부여
 wheat    0.067386
maize    0.057890
cocoa    0.055241
Name: 부여, dtype: float32
천안
 wheat     0.066585
cocoa     0.059119
lentil    0.058439
Name: 천안, dtype: float32
보령
 wheat          0.065605
kidneybeans    0.057891
grapes         0.057514
Name: 보령, dtype: float32
서산
 wheat          0.065605
kidneybeans    0.057891
grapes         0.057514
Name: 서산, dtype: float32
청주
 wheat      0.066156
coconut    0.058444
lentil     0.058009
Name: 청주, dtype: float32
추풍령
 wheat    0.067358
cocoa    0.059483
maize    0.058260
Name: 추풍령, dtype: float32
보은
 wheat     0.074343
cocoa     0.058457
lentil    0.057998
Name: 보은, dtype: float32
제천
 wheat    0.075097
maize    0.064462
rice     0.050669
Name: 제천, dtype: float32
인천
 wheat      0.064775
coconut    0.057069
banana     0.057065
Name: 인천, dtype: float32
강화
 wheat          0.073256
kidneybeans    0.057485
grapes         0.057109
Name: 강화, dtype: float32
수원
 wheat     0.067122
lentil    0.058628
maize     0.058036
Name: 수원, dtype: float32
이천
 wheat     0.066593
lentil    0.058446
maize     0.057494
Name: 이천, dtype: float32
양평
 wheat     0.066593
lentil    0.058446
maize     0.057494
Name: 양평, dtype: float32
광주
 wheat      0.066533
coconut    0.066521
maize      0.057036
Name: 광주, dtype: float32
장흥
 wheat    0.067913
maize    0.058429
cocoa    0.055418
Name: 장흥, dtype: float32
목포
 wheat      0.065684
coconut    0.065134
banana     0.065119
Name: 목포, dtype: float32
해남
 wheat          0.067122
kidneybeans    0.058647
maize          0.058035
Name: 해남, dtype: float32
고흥
 wheat          0.067118
kidneybeans    0.058643
maize          0.058031
Name: 고흥, dtype: float32
완도
 wheat      0.065455
coconut    0.064934
banana     0.064890
Name: 완도, dtype: float32
여수
 banana     0.065682
rice       0.058085
coconut    0.057725
Name: 여수, dtype: float32
전주
 wheat      0.066949
coconut    0.058838
maize      0.057453
Name: 전주, dtype: float32
임실
 wheat    0.074852
maize    0.064601
cocoa    0.054639
Name: 임실, dtype: float32
군산
 coconut    0.065299
wheat      0.065058
banana     0.057022
Name: 군산, dtype: float32
부안
 wheat      0.065773
maize      0.063930
coconut    0.058061
Name: 부안, dtype: float32
정읍
 wheat    0.067386
maize    0.057890
cocoa    0.055241
Name: 정읍, dtype: float32
남원
 wheat          0.075166
maize          0.057470
pomegranate    0.054710
Name: 남원, dtype: float32
장수
 wheat    0.075566
maize    0.057687
cocoa    0.055014
Name: 장수, dtype: float32
부산
 banana         0.065778
wheat          0.058190
kidneybeans    0.058118
Name: 부산, dtype: float32
밀양
 wheat     0.066950
orange    0.058805
maize     0.057453
Name: 밀양, dtype: float32
창원
 wheat      0.066961
coconut    0.058598
maize      0.058148
Name: 창원, dtype: float32
통영
 wheat      0.065426
coconut    0.065016
banana     0.064971
Name: 통영, dtype: float32
거제
 wheat      0.065761
coconut    0.065675
banana     0.057369
Name: 거제, dtype: float32
진주
 wheat          0.075163
maize          0.057467
pomegranate    0.054707
Name: 진주, dtype: float32
산청
 wheat    0.067386
maize    0.057890
cocoa    0.055240
Name: 산청, dtype: float32
남해
 coconut    0.066450
wheat      0.066132
rice       0.057852
Name: 남해, dtype: float32
거창
 wheat    0.075361
maize    0.058074
cocoa    0.054807
Name: 거창, dtype: float32
합천
 wheat     0.066949
orange    0.058804
maize     0.057453
Name: 합천, dtype: float32
울산
 wheat      0.066533
coconut    0.066521
maize      0.057036
Name: 울산, dtype: float32
제주
 papaya    0.061598
wheat     0.059790
cocoa     0.055699
Name: 제주, dtype: float32
고산
 coconut        0.058619
kidneybeans    0.058551
banana         0.058279
Name: 고산, dtype: float32
서귀포
 banana    0.065942
papaya    0.059523
rice      0.058387
Name: 서귀포, dtype: float32
대구
 orange      0.065496
wheat       0.065327
chickpea    0.057644
Name: 대구, dtype: float32
구미
 wheat     0.066595
lentil    0.058448
maize     0.057496
Name: 구미, dtype: float32
문경
 wheat    0.067581
maize    0.058494
cocoa    0.055437
Name: 문경, dtype: float32
영주
 wheat    0.067581
maize    0.058494
cocoa    0.055437
Name: 영주, dtype: float32
봉화
 wheat    0.074869
maize    0.064235
cocoa    0.054665
Name: 봉화, dtype: float32
안동
 wheat     0.066594
lentil    0.058447
maize     0.057495
Name: 안동, dtype: float32
영덕
 wheat     0.066573
lentil    0.058426
maize     0.057883
Name: 영덕, dtype: float32
울진
 wheat    0.067380
cocoa    0.059514
maize    0.057884
Name: 울진, dtype: float32
의성
 wheat          0.074155
pomegranate    0.058225
lentil         0.057809
Name: 의성, dtype: float32
영천
 wheat          0.066356
pomegranate    0.058626
lentil         0.058209
Name: 영천, dtype: float32
포항
 wheat          0.066319
coconut        0.066095
pomegranate    0.057763
Name: 포항, dtype: float32
울릉도
 wheat     0.067277
cocoa     0.059460
grapes    0.058786
Name: 울릉도, dtype: float32
동해
 wheat    0.067224
maize    0.064983
cocoa    0.055076
Name: 동해, dtype: float32
영월
 wheat     0.074351
lentil    0.058005
maize     0.057461
Name: 영월, dtype: float32
흑산도
 coconut        0.058649
kidneybeans    0.058646
wheat          0.057941
Name: 흑산도, dtype: float32
동두천
 wheat     0.066810
lentil    0.058663
maize     0.057711
Name: 동두천, dtype: float32
문산
 wheat     0.067346
lentil    0.058852
maize     0.058260
Name: 문산, dtype: float32
진도
 wheat          0.066326
kidneybeans    0.058249
grapes         0.058232
Name: 진도, dtype: float32
상주
 wheat     0.066595
lentil    0.058448
maize     0.057496
Name: 상주, dtype: float32
고창
 wheat      0.066155
coconut    0.058428
lentil     0.058009
Name: 고창, dtype: float32

In [ ]:
%time df_xg = predict_6m_all_region(3, 2022)

for col in df_xg.columns:
    df_xg = df_xg.sort_values(by=col, ascending=False)
    print(col, '\n', df_xg[col].head(3))

CPU times: user 1min 9s, sys: 467 ms, total: 1min 9s
Wall time: 1min 15s
서울
 wheat          0.065607
kidneybeans    0.057892
grapes         0.057516
Name: 서울, dtype: float32
관악산
 wheat          0.065893
rice           0.057904
kidneybeans    0.057816
Name: 관악산, dtype: float32
춘천
 wheat     0.066429
maize     0.064586
lentil    0.058283
Name: 춘천, dtype: float32
철원
 wheat          0.073012
cocoa          0.057890
kidneybeans    0.057241
Name: 철원, dtype: float32
속초
 wheat     0.067120
grapes    0.058626
maize     0.058033
Name: 속초, dtype: float32
원주
 wheat     0.067121
lentil    0.058627
maize     0.058034
Name: 원주, dtype: float32
대관령
 wheat    0.072875
maize    0.070929
rice     0.064342
Name: 대관령, dtype: float32
태백
 wheat    0.074154
maize    0.063932
cocoa    0.058281
Name: 태백, dtype: float32
인제
 wheat     0.074049
grapes    0.057503
lentil    0.057503
Name: 인제, dtype: float32
홍천
 wheat     0.074283
maize     0.064440
lentil    0.058080
Name: 홍천, dtype: float32
대전
 wheat     0.066430
maize     0.064587
lentil    0.058283
Name: 대전, dtype: float32
금산
 wheat     0.074059
maize     0.064206
lentil    0.057856
Name: 금산, dtype: float32
부여
 wheat     0.067121
lentil    0.058627
maize     0.058034
Name: 부여, dtype: float32
천안
 wheat     0.067121
lentil    0.058627
maize     0.058034
Name: 천안, dtype: float32
보령
 wheat     0.066392
grapes    0.057906
lentil    0.057906
Name: 보령, dtype: float32
서산
 wheat          0.065380
cocoa          0.058324
kidneybeans    0.057666
Name: 서산, dtype: float32
청주
 wheat     0.066430
maize     0.064587
lentil    0.058283
Name: 청주, dtype: float32
추풍령
 wheat     0.067100
lentil    0.058606
maize     0.058412
Name: 추풍령, dtype: float32
보은
 wheat     0.074771
lentil    0.058221
maize     0.057290
Name: 보은, dtype: float32
제천
 wheat     0.074048
grapes    0.057502
lentil    0.057502
Name: 제천, dtype: float32
인천
 wheat     0.066394
grapes    0.057908
lentil    0.057908
Name: 인천, dtype: float32
강화
 wheat     0.074042
grapes    0.057500
lentil    0.057500
Name: 강화, dtype: float32
수원
 wheat          0.065607
kidneybeans    0.057893
grapes         0.057516
Name: 수원, dtype: float32
이천
 wheat     0.066429
maize     0.064585
lentil    0.058282
Name: 이천, dtype: float32
양평
 wheat     0.067100
lentil    0.058606
maize     0.058412
Name: 양평, dtype: float32
광주
 wheat      0.066393
maize      0.064152
coconut    0.057890
Name: 광주, dtype: float32
장흥
 wheat          0.067120
kidneybeans    0.058645
maize          0.058033
Name: 장흥, dtype: float32
목포
 coconut        0.065528
wheat          0.065286
kidneybeans    0.057208
Name: 목포, dtype: float32
해남
 wheat          0.067122
kidneybeans    0.058647
maize          0.058034
Name: 해남, dtype: float32
고흥
 wheat          0.067120
kidneybeans    0.058645
maize          0.058033
Name: 고흥, dtype: float32
완도
 wheat      0.065633
rice       0.057731
coconut    0.057320
Name: 완도, dtype: float32
여수
 coconut    0.067025
rice       0.058761
wheat      0.058370
Name: 여수, dtype: float32
전주
 wheat    0.067222
maize    0.064981
cocoa    0.055075
Name: 전주, dtype: float32
임실
 wheat    0.075563
maize    0.057685
cocoa    0.055011
Name: 임실, dtype: float32
군산
 wheat          0.065831
kidneybeans    0.058117
grapes         0.057740
Name: 군산, dtype: float32
부안
 wheat          0.066327
kidneybeans    0.058251
lentil         0.058232
Name: 부안, dtype: float32
정읍
 wheat    0.067222
maize    0.064981
cocoa    0.055075
Name: 정읍, dtype: float32
남원
 wheat    0.074852
maize    0.064601
cocoa    0.054639
Name: 남원, dtype: float32
장수
 wheat    0.074164
maize    0.063938
cocoa    0.058286
Name: 장수, dtype: float32
부산
 rice       0.058541
wheat      0.058151
coconut    0.058132
Name: 부산, dtype: float32
밀양
 wheat    0.067604
maize    0.058108
cocoa    0.055459
Name: 밀양, dtype: float32
창원
 wheat      0.065420
coconut    0.064899
banana     0.064855
Name: 창원, dtype: float32
통영
 wheat      0.065802
coconut    0.065785
rice       0.057899
Name: 통영, dtype: float32
거제
 wheat          0.066943
rice           0.058631
kidneybeans    0.058468
Name: 거제, dtype: float32
진주
 wheat    0.075564
maize    0.057672
cocoa    0.055012
Name: 진주, dtype: float32
산청
 wheat    0.067380
cocoa    0.059514
maize    0.057883
Name: 산청, dtype: float32
남해
 wheat          0.067119
kidneybeans    0.058644
maize          0.058033
Name: 남해, dtype: float32
거창
 wheat    0.074852
maize    0.064601
cocoa    0.054639
Name: 거창, dtype: float32
합천
 wheat    0.067603
maize    0.058107
cocoa    0.055458
Name: 합천, dtype: float32
울산
 wheat    0.067225
maize    0.064984
cocoa    0.055077
Name: 울산, dtype: float32
제주
 banana         0.065781
wheat          0.058194
kidneybeans    0.058122
Name: 제주, dtype: float32
고산
 coconut        0.059031
kidneybeans    0.058960
wheat          0.058618
Name: 고산, dtype: float32
서귀포
 rice       0.067204
coconut    0.058785
wheat      0.058636
Name: 서귀포, dtype: float32
대구
 wheat     0.066813
lentil    0.058666
maize     0.057715
Name: 대구, dtype: float32
구미
 wheat     0.066811
lentil    0.058664
maize     0.057712
Name: 구미, dtype: float32
문경
 wheat     0.066408
maize     0.064962
lentil    0.058262
Name: 문경, dtype: float32
영주
 wheat    0.067201
maize    0.065358
cocoa    0.055045
Name: 영주, dtype: float32
봉화
 wheat     0.073822
cocoa     0.058309
grapes    0.057276
Name: 봉화, dtype: float32
안동
 wheat     0.066429
maize     0.064586
lentil    0.058283
Name: 안동, dtype: float32
영덕
 wheat     0.066564
cocoa     0.059087
lentil    0.058418
Name: 영덕, dtype: float32
울진
 wheat    0.067221
maize    0.064980
cocoa    0.055074
Name: 울진, dtype: float32
의성
 wheat     0.074590
lentil    0.058244
maize     0.057306
Name: 의성, dtype: float32
영천
 wheat     0.066789
lentil    0.058643
maize     0.058099
Name: 영천, dtype: float32
포항
 wheat      0.067149
coconut    0.059023
maize      0.058036
Name: 포항, dtype: float32
울릉도
 wheat          0.066839
cocoa          0.059022
kidneybeans    0.058781
Name: 울릉도, dtype: float32
동해
 wheat    0.067913
maize    0.058429
cocoa    0.055419
Name: 동해, dtype: float32
영월
 wheat     0.074283
maize     0.064440
lentil    0.058080
Name: 영월, dtype: float32
흑산도
 coconut    0.059308
wheat      0.058599
lentil     0.058513
Name: 흑산도, dtype: float32
동두천
 wheat     0.066429
maize     0.064586
lentil    0.058283
Name: 동두천, dtype: float32
문산
 wheat          0.065606
kidneybeans    0.057892
grapes         0.057515
Name: 문산, dtype: float32
진도
 wheat     0.067057
cocoa     0.059346
grapes    0.058673
Name: 진도, dtype: float32
상주
 wheat     0.066586
cocoa     0.059120
lentil    0.058439
Name: 상주, dtype: float32
고창
 wheat      0.066290
coconut    0.057823
banana     0.057819
Name: 고창, dtype: float32

In [ ]:
%time df_xg = predict_6m_all_region(3, 2100)

for col in df_xg.columns:
    df_xg = df_xg.sort_values(by=col, ascending=False)
    print(col, '\n', df_xg[col].head(3))

CPU times: user 1min 6s, sys: 556 ms, total: 1min 6s
Wall time: 1min 13s
서울
 wheat      0.066671
coconut    0.058220
banana     0.058210
Name: 서울, dtype: float32
관악산
 wheat          0.065890
rice           0.058279
kidneybeans    0.057813
Name: 관악산, dtype: float32
춘천
 wheat     0.066810
lentil    0.058663
maize     0.057711
Name: 춘천, dtype: float32
철원
 wheat     0.06640
grapes    0.05791
lentil    0.05791
Name: 철원, dtype: float32
속초
 wheat    0.067379
cocoa    0.059515
maize    0.057883
Name: 속초, dtype: float32
원주
 wheat     0.066593
lentil    0.058446
maize     0.057494
Name: 원주, dtype: float32
대관령
 wheat     0.075296
grapes    0.058402
maize     0.057829
Name: 대관령, dtype: float32
태백
 wheat          0.073527
cocoa          0.062328
kidneybeans    0.057393
Name: 태백, dtype: float32
인제
 wheat     0.074589
lentil    0.058243
maize     0.057305
Name: 인제, dtype: float32
홍천
 wheat     0.074350
lentil    0.058004
maize     0.057460
Name: 홍천, dtype: float32
대전
 wheat      0.067166
coconut    0.059057
maize      0.057670
Name: 대전, dtype: float32
금산
 wheat    0.075360
maize    0.058073
cocoa    0.054806
Name: 금산, dtype: float32
부여
 wheat    0.067386
maize    0.057890
cocoa    0.055241
Name: 부여, dtype: float32
천안
 wheat     0.066585
cocoa     0.059119
lentil    0.058439
Name: 천안, dtype: float32
보령
 wheat          0.065605
kidneybeans    0.057891
grapes         0.057514
Name: 보령, dtype: float32
서산
 wheat          0.065605
kidneybeans    0.057891
grapes         0.057514
Name: 서산, dtype: float32
청주
 wheat      0.066156
coconut    0.058444
lentil     0.058009
Name: 청주, dtype: float32
추풍령
 wheat    0.067358
cocoa    0.059483
maize    0.058260
Name: 추풍령, dtype: float32
보은
 wheat     0.074343
cocoa     0.058457
lentil    0.057998
Name: 보은, dtype: float32
제천
 wheat    0.075097
maize    0.064462
rice     0.050669
Name: 제천, dtype: float32
인천
 wheat      0.064775
coconut    0.057069
banana     0.057065
Name: 인천, dtype: float32
강화
 wheat          0.073256
kidneybeans    0.057485
grapes         0.057109
Name: 강화, dtype: float32
수원
 wheat     0.067122
lentil    0.058628
maize     0.058036
Name: 수원, dtype: float32
이천
 wheat     0.066593
lentil    0.058446
maize     0.057494
Name: 이천, dtype: float32
양평
 wheat     0.066593
lentil    0.058446
maize     0.057494
Name: 양평, dtype: float32
광주
 wheat      0.066533
coconut    0.066521
maize      0.057036
Name: 광주, dtype: float32
장흥
 wheat    0.067913
maize    0.058429
cocoa    0.055418
Name: 장흥, dtype: float32
목포
 wheat      0.065684
coconut    0.065134
banana     0.065119
Name: 목포, dtype: float32
해남
 wheat          0.067122
kidneybeans    0.058647
maize          0.058035
Name: 해남, dtype: float32
고흥
 wheat          0.067118
kidneybeans    0.058643
maize          0.058031
Name: 고흥, dtype: float32
완도
 wheat      0.065455
coconut    0.064934
banana     0.064890
Name: 완도, dtype: float32
여수
 banana     0.065682
rice       0.058085
coconut    0.057725
Name: 여수, dtype: float32
전주
 wheat      0.066949
coconut    0.058838
maize      0.057453
Name: 전주, dtype: float32
임실
 wheat    0.074852
maize    0.064601
cocoa    0.054639
Name: 임실, dtype: float32
군산
 coconut    0.065299
wheat      0.065058
banana     0.057022
Name: 군산, dtype: float32
부안
 wheat      0.065773
maize      0.063930
coconut    0.058061
Name: 부안, dtype: float32
정읍
 wheat    0.067386
maize    0.057890
cocoa    0.055241
Name: 정읍, dtype: float32
남원
 wheat          0.075166
maize          0.057470
pomegranate    0.054710
Name: 남원, dtype: float32
장수
 wheat    0.075566
maize    0.057687
cocoa    0.055014
Name: 장수, dtype: float32
부산
 banana         0.065778
wheat          0.058190
kidneybeans    0.058118
Name: 부산, dtype: float32
밀양
 wheat     0.066950
orange    0.058805
maize     0.057453
Name: 밀양, dtype: float32
창원
 wheat      0.066961
coconut    0.058598
maize      0.058148
Name: 창원, dtype: float32
통영
 wheat      0.065426
coconut    0.065016
banana     0.064971
Name: 통영, dtype: float32
거제
 wheat      0.065761
coconut    0.065675
banana     0.057369
Name: 거제, dtype: float32
진주
 wheat          0.075163
maize          0.057467
pomegranate    0.054707
Name: 진주, dtype: float32
산청
 wheat    0.067386
maize    0.057890
cocoa    0.055240
Name: 산청, dtype: float32
남해
 coconut    0.066450
wheat      0.066132
rice       0.057852
Name: 남해, dtype: float32
거창
 wheat    0.075361
maize    0.058074
cocoa    0.054807
Name: 거창, dtype: float32
합천
 wheat     0.066949
orange    0.058804
maize     0.057453
Name: 합천, dtype: float32
울산
 wheat      0.066533
coconut    0.066521
maize      0.057036
Name: 울산, dtype: float32
제주
 papaya    0.061598
wheat     0.059790
cocoa     0.055699
Name: 제주, dtype: float32
고산
 coconut        0.058619
kidneybeans    0.058551
banana         0.058279
Name: 고산, dtype: float32
서귀포
 banana    0.065942
papaya    0.059523
rice      0.058387
Name: 서귀포, dtype: float32
대구
 orange      0.065496
wheat       0.065327
chickpea    0.057644
Name: 대구, dtype: float32
구미
 wheat     0.066595
lentil    0.058448
maize     0.057496
Name: 구미, dtype: float32
문경
 wheat    0.067581
maize    0.058494
cocoa    0.055437
Name: 문경, dtype: float32
영주
 wheat    0.067581
maize    0.058494
cocoa    0.055437
Name: 영주, dtype: float32
봉화
 wheat    0.074869
maize    0.064235
cocoa    0.054665
Name: 봉화, dtype: float32
안동
 wheat     0.066594
lentil    0.058447
maize     0.057495
Name: 안동, dtype: float32
영덕
 wheat     0.066573
lentil    0.058426
maize     0.057883
Name: 영덕, dtype: float32
울진
 wheat    0.067380
cocoa    0.059514
maize    0.057884
Name: 울진, dtype: float32
의성
 wheat          0.074155
pomegranate    0.058225
lentil         0.057809
Name: 의성, dtype: float32
영천
 wheat          0.066356
pomegranate    0.058626
lentil         0.058209
Name: 영천, dtype: float32
포항
 wheat          0.066319
coconut        0.066095
pomegranate    0.057763
Name: 포항, dtype: float32
울릉도
 wheat     0.067277
cocoa     0.059460
grapes    0.058786
Name: 울릉도, dtype: float32
동해
 wheat    0.067224
maize    0.064983
cocoa    0.055076
Name: 동해, dtype: float32
영월
 wheat     0.074351
lentil    0.058005
maize     0.057461
Name: 영월, dtype: float32
흑산도
 coconut        0.058649
kidneybeans    0.058646
wheat          0.057941
Name: 흑산도, dtype: float32
동두천
 wheat     0.066810
lentil    0.058663
maize     0.057711
Name: 동두천, dtype: float32
문산
 wheat     0.067346
lentil    0.058852
maize     0.058260
Name: 문산, dtype: float32
진도
 wheat          0.066326
kidneybeans    0.058249
grapes         0.058232
Name: 진도, dtype: float32
상주
 wheat     0.066595
lentil    0.058448
maize     0.057496
Name: 상주, dtype: float32
고창
 wheat      0.066155
coconut    0.058428
lentil     0.058009
Name: 고창, dtype: float32